language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - MONGO_VERSION=1.3.0
  - MONGO_VERSION=1.4.0
  - MONGO_VERSION=1.5.0
  - MONGO_VERSION=stable

services:
  - mongodb

before_script:
  - yes '' | pecl -q install -f mongo-${MONGO_VERSION}
  - php --ri mongo
  - composer install --dev --no-interaction --prefer-source

script:
  - ./vendor/behat/behat/bin/behat -fprogress --strict